{% set name = "scdoc" %}
{% set version = "1.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.sr.ht/~sircmpwn/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4c5c6136540384e5455b250f768e7ca11b03fdba1a8efc2341ee0f1111e57612

build:
  skip: True  # [win]
  script:
    - make install LDFLAGS= PREFIX=$PREFIX
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - ncurses

test:
  commands:
    - test -f $PREFIX/bin/scdoc

about:
  home: https://sr.ht/~sircmpwn/scdoc/
  summary: Small man page generator
  license: MIT
  license_family: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - pavelzw
